_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 49
                - 55
                - 95
            "2":
                - 49
                - 55
                - 95
            "3":
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-x86_64
